### ISSUE TITLE
Means to serialize or synchronize JSON data with y-map

### ISSUE THREAD

**Issue by Flaminator89** [y-js/y-map#9]
I'm looking to keep a JSON array synchronized across clients using YJS and y-map fits the bill.  However, in my application I would would prefer to keep the array type which the client directly manipulates and reads from as JSON since it is easier to plug in to other libraries.

From my understanding currently there is no way to 'synchronize' the y-map with a JSON array, is that correct?  If so would something that does that be in the scope of this data type (i.e. a serialize/deserialize) or would a separate library be a better place?

**Comment by Flaminator89** [comment]
Actually i think i may be thinking about this wrong.... the json array should juat be an elememt in the yjsmap i suppose...?

**Comment by dmonad** [comment]
Both is possible. It depends on your use-case.

**Option 1**
Of course you can represent JSON using of Y.Map & Y.Array. There were several approaches to work with plain JSON objects instead of Yjs types: I.e. shared properties in [y-element](https://github.com/y-js/y-element), and [yubiquity](https://github.com/lukebarlow/yubiquity) (unfortunately unmaintained).

You can leverage the `observePath` method to observe sub-properties. But you have to handle data serialization.

**Option 2**
If it suffices for your application, you are perfectly fine implementing your second approach. The only downside would be that you also overwrite data that hasn't changed (increasing bandwidth usage a bit)

**Comment by Flaminator89** [comment]
Option 1 seems like a great choice!  Hadn't used polymer before, but that will actually work perfectly for my use case... I'm having a bit of an issue trying to get up and running but I'll post that on the issue board for y-element.  Thanks for pointing me in the right direction!
